### ISSUE TITLE
not logged user can see reply button

### ISSUE THREAD

**Issue by sinanisler** [sinanisler/SiForum#20]
not logged user can see reply button

**Comment by Hari-Bonda** [comment]
Users should see a reply button when not logged in.
if not logged in users should be taken to the login page or offer an inline popup to log in.

**Comment by sinanisler** [comment]
yeah it shows "login to reply" on flarum
I was thinking do like that too but it looked cleaner like this :)
I wanted to keep minimalist
![image](https://user-images.githubusercontent.com/1686324/167452576-f36f9776-e88f-4a17-b3e5-969a1b785b8e.png)

profile/login  sinanisler/SiForum#8

**Comment by sinanisler** [comment]
https://github.com/sinanisler/SiForum/commit/d0dc8273c2beee1f3fea9d1bae2ae4d9496e0b76

added
