### ISSUE TITLE
Mobile compatibility

### ISSUE THREAD

**Issue by Hari-Bonda** [sinanisler/SiForum#28]
Mobile compatibility

**Comment by sinanisler** [comment]
except header menu mobile good on everywhere.
the menu will be mobile-friendly too..

![image](https://user-images.githubusercontent.com/1686324/168178780-7f89d1cf-7ce7-4d79-89ce-68782d9d5977.png)

**Comment by Hari-Bonda** [comment]
> except header menu mobile good on everywhere.
> the menu will be mobile-friendly too..
> 
> ![image](https://user-images.githubusercontent.com/1686324/168178780-7f89d1cf-7ce7-4d79-89ce-68782d9d5977.png)
> 
> 
> ![image](https://user-images.githubusercontent.com/1686324/168178940-6faf7e55-6d02-46f3-86f8-38f77cc89251.png)
> 

Open in actual mobile browser, if there are images everything is getting disturbed.

If we check using dev tools it's looking okayish

**Comment by Hari-Bonda** [comment]
![Screenshot_20220513-042101~2.png](https://user-images.githubusercontent.com/5230394/168180161-1e9afbc5-7602-4444-8b78-1c3e5dbdd9b3.png)

**Comment by Hari-Bonda** [comment]
![Screenshot_20220513-042244.jpg](https://user-images.githubusercontent.com/5230394/168180292-24d0431f-1c96-4156-94d3-7da4a8455837.jpg)

**Comment by sinanisler** [comment]
I am testing on mobile while coding 
these are from my phone screenshots

![image](https://user-images.githubusercontent.com/1686324/168311342-0dfa40f0-94d9-46ea-8c67-d3f5d69b7a95.png)
![image](https://user-images.githubusercontent.com/1686324/168311363-fc580e81-92b0-42db-ba22-d515cf40e3b3.png)
![image](https://user-images.githubusercontent.com/1686324/168311393-37f84679-31fd-4ea7-92ea-cab722751b28.png)

it is normal for a code to show like that btw

**Comment by sinanisler** [comment]
I tested on chrome and opera
no big issues. (only menu not done yet but like i said menu will have mobile button later...)

update your apps 
clear cache too phones cache heavily..

**Comment by Hari-Bonda** [comment]
It's happening when there are many images in the discussion. I will check in private browsing
