### ISSUE TITLE
Dedicated pages for all categories, following - Feature Request

### ISSUE THREAD

**Issue by Hari-Bonda** [sinanisler/SiForum#3]
![image](https://user-images.githubusercontent.com/5230394/166407211-815fa8b0-18a9-4ac9-971f-ddb9c85799b4.png)

https://discuss.flarum.org/tags

Dedicated pages for all categories, following page

**Comment by sinanisler** [comment]
this is easy thing to do but problem is Wordpress hierarchy doesn't have dedicated all archive page. 

but it is possible to make this as a simple css/html/js 

[wp](https://developer.wordpress.org/files/2014/10/Screenshot-2019-01-23-00.20.04.png)

**Comment by sinanisler** [comment]
this is possible to make as a custom  Gutenberg blocks designed page and page link can be put here with new <li> </li>

https://github.com/sinanisler/SiForum/blob/31b03ebaba95bac87f504e2c550c4bed5d7382b3/sidecategories.php#L20
