### ISSUE TITLE
FontAwesome icons

### ISSUE THREAD

**Issue by Hari-Bonda** [sinanisler/SiForum#31]
allow us to use or define font awsome icons in theme settings for lock, pin 

hoping all colours and icons settings can be tuned in the admin panel 

this theme is super fast without CF and APO .. i can't imagine how fast it is going to be if it is optimised 🚀 great work.

![image](https://user-images.githubusercontent.com/5230394/168840478-8f1398df-7a32-45c7-8419-5567c1eebedb.png)

**Comment by sinanisler** [comment]
thats easy https://wordpress.org/plugins/font-awesome/ install this and 
just change the span class that's it...

but dashicons are good man https://wordpress.org/plugins/font-awesome/
