### ISSUE TITLE
set home page icon link to own domain

### ISSUE THREAD

**Issue by Hari-Bonda** [sinanisler/SiForum#47]
need to remove atarikafa.com link from various files

https://github.com/sinanisler/SiForum/blob/d235d4b5e1475bbe6bdec2e4debe033e32d141ba/header.php#L21

https://github.com/sinanisler/SiForum/search?q=atarikafa.com

**Comment by sinanisler** [comment]
we have to put a some kind of example domain or text havent we ? :)

**Comment by sinanisler** [comment]
closing this for now.

**other logo and url thing will be fixed with customizer setting.**

**Comment by Hari-Bonda** [comment]
it should be our own domain name na 🙂, i have visited customizer settings and did not find a way to modify the logo URL. anyway, i will try again, maybe i am looking in the wrong place.

![image](https://user-images.githubusercontent.com/5230394/179423820-3f7d5b60-bb51-497a-84d4-0f9163d6b6ff.png)
