### ISSUE TITLE
hide comment reply section when post locked 

### ISSUE THREAD

**Issue by sinanisler** [sinanisler/SiForum#63]
hide comment reply section when post locked 

![image](https://user-images.githubusercontent.com/1686324/182708729-7e83c263-27c1-4395-b2b2-5519e958734e.png)

**Comment by Hari-Bonda** [comment]
We should display something like this 🐱‍👤

![image](https://user-images.githubusercontent.com/5230394/184505848-4ff817c4-06cc-4a37-aac1-56e47b0188d6.png)
