### ISSUE TITLE
FontAwesome support for categories icons

### ISSUE THREAD

**Issue by Hari-Bonda** [sinanisler/SiForum#66]
There are only a few icons in the WordPress https://developer.wordpress.org/resource/dashicons/

It would be great if you allow to use FontAwesome icons like flarum

**Comment by sinanisler** [comment]
dashicon not as big as fontawesome but it has every type of icon man :)

fontawesome will add 90kb I will think about :)

**Comment by sinanisler** [comment]
Solid https://fontawesome.com/search?s=solid

**Comment by Hari-Bonda** [comment]
yeah, I have tried it, but it's not working. add another field for FA icons 💓

![image](https://user-images.githubusercontent.com/5230394/186006005-e8253965-e6b8-4976-bf1e-19a83f3b42c0.png)

**Comment by serkanalgur** [comment]
Fixed via #69
