### ISSUE TITLE
allow to use any text capitalization in menu

### ISSUE THREAD

**Issue by Hari-Bonda** [sinanisler/SiForum#70]
i have created a hyperlink in menu called **Blog** but for some reason the capitlization of the text is not as expected it is turning all text to Uppercase letters example: **BLOG**

![image](https://user-images.githubusercontent.com/5230394/186018034-7d783150-0500-4693-80b1-2d78fe423ab2.png)

**Comment by sinanisler** [comment]
https://github.com/sinanisler/SiForum/blob/main/style.css#L105

**Comment by Hari-Bonda** [comment]
thanks for the quick response, i have commented that line now everhting is working as expected.  👍

/*  text-transform: uppercase; */
